Nice_Admin_Theme/Models/ErrorViewModel.cs
using System;

namespace Nice_Admin_Theme.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nice_Admin_Theme/Controllers/NiceAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Nice_Admin_Theme.Controllers
{
    public class NiceAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        public IActionResult FormValidation()
        {
            return View();
        }

        public IActionResult FormComponent()
        {
            return View();
        }

        public IActionResult Button()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Blank()
        {
            return View();
        }

        public IActionResult Error404()
        {
            return View();
        }

        public IActionResult BasicTable()
        {
            return View();
        }

        public IActionResult Chart()
        {
            return View();
        }

        public IActionResult Widget()
        {
            return View();
        }

        public IActionResult Element()
        {
            return View();
        }

        public IActionResult Grid()
        {
            return View();
        }
    }
}

Nice_Admin_Theme/Views/NiceAdmin/Blank.cshtml
@{
    ViewData["Title"] = "Blank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa fa-bars"></i> Pages</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a asp-controller="NiceAdmin" asp-action="Index">Home</a></li>
                    <li><i class="fa fa-bars"></i>Pages</li>
                    <li><i class="fa fa-square-o"></i>Pages</li>
                </ol>
            </div>
        </div>
        <!-- page start-->
        Page content goes here
        <!-- page end-->
    </section>
</section>
<!--main content end-->

Nice_Admin_Theme/Views/NiceAdmin/Chart.cshtml
@{
    ViewData["Title"] = "Chart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="icon_piechart"></i> Chart</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a asp-controller="NiceAdmin" asp-action="Index">Home</a></li>
                    <li><i class="icon_piechart"></i>Chart</li>

                </ol>
            </div>
        </div>
        <div class="row">
            <!-- chart morris start -->
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h3>General Chart</Char>
                    </header>
                    <div class="panel-body">
                        <div class="tab-pane" id="chartjs">
                            <div class="row">
                                <!-- Line -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Line
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="line" height="300" width="450"></canvas>
                                        </div>
                                    </section>
                                </div>
                                <!-- Bar -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Bar
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="bar" height="300" width="500"></canvas>
                                        </div>
                                    </section>
                                </div>
                            </div>
                            <div class="row">
                                <!-- Radar -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Radar
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="radar" height="300" width="400"></canvas>
                                        </div>
                                    </section>
                                </div>
                                <!-- Polar Area -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Polar Area
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="polarArea" height="300" width="400"></canvas>
                                        </div>
                                    </section>
                                </div>
                            </div>
                            <div class="row">

                                <!-- Pie -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Pie
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="pie" height="300" width="400"></canvas>
                                        </div>
                                    </section>
                                </div>
                                <!-- Doughnut -->
                                <div class="col-lg-6">
                                    <section class="panel">
                                        <header class="panel-heading">
                                            Doughnut
                                        </header>
                                        <div class="panel-body text-center">
                                            <canvas id="doughnut" height="300" width="400"></canvas>
                                        </div>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
    </section>
    </div>
    <!-- chart morris start -->
    </div>
</section>
<!--main content end-->

Nice_Admin_Theme/Views/NiceAdmin/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa fa-bars"></i> Pages</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a asp-controller="NiceAdmin" asp-action="Index">Home</a></li>
                    <li><i class="fa fa-bars"></i>Pages</li>
                    <li><i class="fa fa-square-o"></i>Pages</li>
                </ol>
            </div>
        </div>
        <!-- page start-->
        <div class="row">
            <div class="col-lg-6">
                <div class="recent">
                    <h3>Send us a message</h3>
                </div>
                <div id="sendmessage">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>
                <form action="" method="post" role="form" class="contactForm">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                        <div class="validation"></div>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                        <div class="validation"></div>
                    </div>

                    <div class="text-center"><button type="submit" class="btn btn-primary btn-lg">Send Message</button></div>
                </form>
            </div>

            <div class="col-lg-6">
                <div class="recent">
                    <h3>Get in touch with us</h3>
                </div>
                <div class="">
                    <p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum.</p>
                    <p>Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum.</p>

                    <h4>Address:</h4>Little Lonsdale St, New York<br>
                    <h4>Telephone:</h4>345 578 59 45 416</br>
                    <h4>Fax:</h4>123 456 789
                </div>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

Nice_Admin_Theme/Views/NiceAdmin/FormValidation.cshtml
@{
    ViewData["Title"] = "FormValidation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa-files-o"></i> Form Validation</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a asp-controller="NiceAdmin" asp-action="Index">Home</a></li>
                    <li><i class="icon_document_alt"></i>Forms</li>
                    <li><i class="fa fa-files-o"></i>Form Validation</li>
                </ol>
            </div>
        </div>
        <!-- Form validations -->
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Form validations
                    </header>
                    <div class="panel-body">
                        <div class="form">
                            <form class="form-validate form-horizontal" id="feedback_form" method="get" action="">
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Full Name <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control" id="cname" name="fullname" minlength="5" type="text" required />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cemail" class="control-label col-lg-2">E-Mail <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="cemail" type="email" name="email" required />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="curl" class="control-label col-lg-2">Website</label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="curl" type="url" name="url" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="cname" class="control-label col-lg-2">Subject <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control" id="subject" name="subject" minlength="5" type="text" required />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="ccomment" class="control-label col-lg-2">Feedback</label>
                                    <div class="col-lg-10">
                                        <textarea class="form-control " id="ccomment" name="comment" required></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-primary" type="submit">Save</button>
                                        <button class="btn btn-default" type="button">Cancel</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">
                        Advanced Form validations
                    </header>
                    <div class="panel-body">
                        <div class="form">
                            <form class="form-validate form-horizontal " id="register_form" method="get" action="">
                                <div class="form-group ">
                                    <label for="fullname" class="control-label col-lg-2">Full name <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class=" form-control" id="fullname" name="fullname" type="text" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="address" class="control-label col-lg-2">Address <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class=" form-control" id="address" name="address" type="text" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="username" class="control-label col-lg-2">Username <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="username" name="username" type="text" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="password" class="control-label col-lg-2">Password <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="password" name="password" type="password" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="confirm_password" class="control-label col-lg-2">Confirm Password <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="confirm_password" name="confirm_password" type="password" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="email" class="control-label col-lg-2">Email <span class="required">*</span></label>
                                    <div class="col-lg-10">
                                        <input class="form-control " id="email" name="email" type="email" />
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="agree" class="control-label col-lg-2 col-sm-3">Agree to Our Policy <span class="required">*</span></label>
                                    <div class="col-lg-10 col-sm-9">
                                        <input type="checkbox" style="width: 20px" class="checkbox form-control" id="agree" name="agree" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-primary" type="submit">Save</button>
                                        <button class="btn btn-default" type="button">Cancel</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <!-- page end-->
    </section>

</section>
<!--main content end-->

Nice_Admin_Theme/Views/NiceAdmin/Grid.cshtml
@{
    ViewData["Title"] = "Grid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--main content start-->
<section id="main-content">
    <section class=" wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa-tasks"></i> Grids</h3>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a asp-controller="NiceAdmin" asp-action="Index">Home</a></li>
                    <li><i class="fa fa-desktop"></i>UI Fitures</li>
                    <li><i class="fa fa-tasks"></i>Grids</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h4>Grid System - Base on Bootstrap grid system.</h4>
            </div>
            <div class="col-lg-12">
                <section class="panel">
                    <div class="panel-body">col-lg-12</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <div class="panel-body">col-lg-6</div>
                </section>
            </div>
            <div class="col-lg-6">
                <section class="panel">
                    <div class="panel-body">col-lg-6</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <section class="panel">
                    <div class="panel-body">col-lg-4</div>
                </section>
            </div>
            <div class="col-lg-4">
                <section class="panel">
                    <div class="panel-body">col-lg-4</div>
                </section>
            </div>
            <div class="col-lg-4">
                <section class="panel">
                    <div class="panel-body">col-lg-4</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3">
                <section class="panel">
                    <div class="panel-body">col-lg-3</div>
                </section>
            </div>
            <div class="col-lg-3">
                <section class="panel">
                    <div class="panel-body">col-lg-3</div>
                </section>
            </div>
            <div class="col-lg-3">
                <section class="panel">
                    <div class="panel-body">col-lg-3</div>
                </section>
            </div>
            <div class="col-lg-3">
                <section class="panel">
                    <div class="panel-body">col-lg-3</div>
                </section>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
            <div class="col-lg-2">
                <section class="panel">
                    <div class="panel-body">col-lg-2</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <p>Mobile, tablet, and desktop</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="row">
                    <div class="col-xs-6">
                        <section class="panel">
                            <div class="panel-body">col-xs-6</div>
                        </section>
                    </div>
                    <div class="col-xs-6">
                        <section class="panel">
                            <div class="panel-body">col-xs-6</div>
                        </section>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <section class="panel">
                    <div class="panel-body">col-lg-8</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-sm-6">
                        <section class="panel">
                            <div class="panel-body">col-sm-6</div>
                        </section>
                    </div>
                    <div class="col-sm-6">
                        <section class="panel">
                            <div class="panel-body">col-sm-6</div>
                        </section>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <section class="panel">
                    <div class="panel-body">col-lg-6</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-md-6">
                        <section class="panel">
                            <div class="panel-body">col-md-6</div>
                        </section>
                    </div>
                    <div class="col-md-6">
                        <section class="panel">
                            <div class="panel-body">col-md-6</div>
                        </section>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <section class="panel">
                    <div class="panel-body">col-lg-4</div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <section class="panel">
                    <div class="panel-body">col-sm-6</div>
                </section>
            </div>
            <div class="col-sm-6">
                <section class="panel">
                    <div class="panel-body">col-sm-6</div>
                </section>
            </div>
        </div>
    </section>
</section>
<!--main content end-->

Nice_Admin_Theme/Views/Shared/_Sidebar.cshtml
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
            <li class="active">
                <a class="" asp-controller="NiceAdmin" asp-action="Index">
                    <i class="icon_house_alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_document_alt"></i>
                    <span>Forms</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" asp-controller="NiceAdmin" asp-action="FormComponent">Form Elements</a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="FormValidation">Form Validation</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_desktop"></i>
                    <span>UI Fitures</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Element">Elements</a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Button">Buttons</a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Grid">Grids</a></li>
                </ul>
            </li>
            <li>
                <a class="" asp-controller="NiceAdmin" asp-action="Widget">
                    <i class="icon_genius"></i>
                    <span>Widgets</span>
                </a>
            </li>
            <li>
                <a class="" asp-controller="NiceAdmin" asp-action="Chart">
                    <i class="icon_piechart"></i>
                    <span>Charts</span>

                </a>

            </li>

            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_table"></i>
                    <span>Tables</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" asp-controller="NiceAdmin" asp-action="BasicTable">Basic Table</a></li>
                </ul>
            </li>

            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_documents_alt"></i>
                    <span>Pages</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" asp-action="Profile" asp-controller="NiceAdmin">Profile</a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Login"><span>Login Page</span></a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Contact"><span>Contact Page</span></a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Blank">Blank Page</a></li>
                    <li><a class="" asp-controller="NiceAdmin" asp-action="Error404">404 Error</a></li>
                </ul>
            </li>

        </ul>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->